include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    deprecated_member_use: ignore
    unnecessary_import: ignore
    unused_import: ignore ignore ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore
